version: "3"
services:
  postgres_db:
    image: postgres:11
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_demo
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8888:80"
    depends_on:
      - postgres_db
      - cache
  
  cache:
    image: "redis:alpine"
    ports:
      - "637:6379"
